---
# Variable configuration
- include_tasks: variables.yml

# Setup/install tasks
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: build.yml
#- include_tasks: initialize.yml

# TODO: - include_tasks: configure.yml

# TODO: enable services using a list variable and with_items
# - name: Ensure Plantd Unit is started and enabled on boot.
#   systemd:
#     name: "{{ plantd_unit_daemon }}"
#     state: "{{ plantd_unit_service_state }}"
#     enabled: "{{ plantd_unit_service_enabled }}"
#   tags: [ "plantd-unit" ]

# Configure Plantd Unit
#- import_tasks: databases.yml
#- import_tasks: users.yml
